[package]
name = "yast"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dyn-clone = "1.0.20"
iced = { version = "0.14.0", features = ["advanced", "tokio", "image"] }
iced_aw = { version = "0.13.0", features = ["context_menu", "color_picker"] }
livesplit-core = "0.13.0"
log = "0.4.29"
mlua = { version = "0.11.6", features = ["lua54", "vendored", "error-send", "anyhow"] }
pretty_env_logger = "0.5.0"
global-hotkey = "0.7.0"
rfd = "0.17.2"
serde = "1.0.228"
toml = "0.9.11"
dirs = "6.0.0"
