[package]
name = "yast"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
iced = { version = "0.14.0", features = ["advanced", "tokio"] }
livesplit-core = "0.13.0"
log = "0.4.29"
mlua = { version = "0.11.6", features = ["lua54", "vendored", "error-send", "anyhow"] }
pretty_env_logger = "0.5.0"
